theme: jekyll-theme-primer
title: Project summary
description: This project is to build and evaluate classification models to predict reversion from mild cognitive impairment (MCI) to normal cognitive functioning within 2 years (a binary outcome) using the ADNI (Alzheimer’s Disease Neuroimaging Initiative) database.
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
